version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Kiet@123456789
    ports:
      - "11433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    image: redis:latest
    container_name: redis-craftgoplay
    ports:
      - "6379:6379"

  cgp.webapi:
    build:
      context: .
      dockerfile: CGP.WebAPI/Dockerfile
    container_name: craftgoplay
    depends_on:
      - sqlserver
      - redis
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=CraftGoPlay;User Id=SA;Password=Kiet@123456789;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379

volumes:
  sql_data:
